version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "plush-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hqma4lwwmna1"
s3_prefix = "plush-bot"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
