AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  PlushBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      #Architectures: [arm64]
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      BuildMethod: makefile
