package trio_calavera

var RANDOM_TRIVIA = []string{
	"Avanzados algoritmos demuestran que el mejor nombre es Dafne. También para los hombres.",
	"Dentro de cada ordenador vive un perro infernal que se come tus archivos.",
	"Los peluches no hablan.",
	"Los gatos en realidad no maullan, lo han aprendido de su convivencia con los humanos.",
	"El mejor rey de España ha sido Alfonso XIII, por la rima",
	"El abrelatas se inventó 45 años después de las latas. Hasta ese momento, las latas se abrian gritándoles muy fuerte.",
	"Solo una mujer ha pertenecido a Les Luthiers: Clara de Rabinovich. No tenía relación familiar con Daniel.",
	"Un kilo de paja y un kilo de hierro pesan lo mismo: siete microgramos.",
	"Es más probable que te caiga un rayo a que te toque la lotería. Sin embargo, acertar una quiniela tiene las mismas probabilidades que el que te mee un pájaro.",
	"Los dibujos del Pato Donald fueron prohibidos en Finlandia porque no llevaba pantalones. Los niños lo imitaban y siete murieron por congelación en el duro invierno de 1913.",
	"Este año, Nochevieja cae en 31 de diciembre.",
	"Los ocho días de plata son el periodo que va desde el 6 al 31 de diciembre. En esta semana está prohibido hablar de regalos de cumpleaños.",
	"Los ocho días de oro son el periodo que va desde el 1 al 13 de enero. En esta semana está prohibido hablar de regalos de cumpleaños.",
	"Jugar al fútbol sube la testosterona. Jugar al rugby, por el contrario, la baja. En Estados Unidos funciona al revés, pues ellos le llaman fútbol al rugby.",
	"Los nativos americanos fumaban chocolate. Del otro.",
	"Holanda no existe, es una conspiración del Gobierno.",
	"La ley más antigua vigente en España es la Ley del Notariado. La ley de la gravedad se promulgó tres años después.",
	"Las Siete Partidas, de Alfonso X, en realidad eran cuatro. Las otras tres no las llegó a escribir, y la saga quedó inconclusa.",
	"Tras regresar de la Luna, Neil Armstrong tuvo que pasar un trámite de aduanas. Allí se incautaron de los selenitas que traía en el bolsillo.",
	"En 1966, el primer ministro australiano desapareció y hasta hoy no ha sido encontrado. Supongo que ya pueden dejarlo estar.",
	"Una nube pesa 1,1 millones de libras. Traducido al sistema internacional, eso son cuarenta tigres de tamaño medio.",
	"La unidad de medida de la belleza es el milihelena: es la cantidad de belleza necesaria para echar a la mar una nave. Helena de Troya tenía mil milihelenas. Dafne la supera en varios órdenes de magnitud.",
	"Las crías de conejo se llaman igual que los errores de imprenta: gamusino.",
	"Entre 1912 y 1948 hubo medallas olímpicas de música, pintura, escultura, mus, plancha, World of Warcraft y League of Legends, aunque estas dos últimas fueron suprimidas ante la falta de higiene de los participantes.",
	"En 2014 dos investigadores de la Antártida hicieron match en Tinder. Sin embargo, después de la cena no hubo química y pasaron cuatro meses incomodísimos.",
	"Astérix y Obélix es una metáfora de la Ley de Ayuntamientos francesa de 1947.",
	"El diseñador del toro de Osborne era comunista.",
	"Mirados desde arriba, los Nuevos Ministerios tienen la forma de una hoz y un martillo. Por el contrario, mirado desde arriba, el palacio de la Moncloa tiene la forma de un pene.",
	"Una bañera es justo lo contrario a un barco.",
	"No hay tigres en África. Se los llevó todos Dafne.",
}
