{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plush-bot.configMapName" . }}
  labels:
    {{- include "plush-bot.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  DYNAMODB_REGION: {{ .Values.plushBot.config.dynamodbRegion }}
  DYNAMODB_TABLE: {{ .Values.plushBot.config.dynamodbTable }}
  RANDOM_MIN_SECONDS: {{ .Values.plushBot.config.randomMinSeconds | quote }}
  RANDOM_MAX_SECONDS: {{ .Values.plushBot.config.randomMaxSeconds | quote }}
{{- end }}
